name: Bot Mail Draft

on:
  workflow_dispatch:
    inputs:
      nombreArchivo:
        description: "Nombre del archivo Excel a descargar. (Dejar extensión .xlsx)"
        required: true
        default: ".xlsx"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Crear archivo de credenciales (service-account.json)
        run: echo "${{ secrets.DRIVE_KEY }}" | base64 -d > service-account.json

      - name: Instalar dependencias
        run: npm install

      - name: Descargar archivo Excel desde Drive
        env:
          nombreArchivo: ${{ github.event.inputs.nombreArchivo }}
        run: node src/script/descargarExcel.js

      - name: Procesar Excel, generar contenido IA y subir DOCX
        env:
          nombreArchivo: ${{ github.event.inputs.nombreArchivo }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: node src/script/procesarExcel.js